# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import moneyops_pb2 as moneyops__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in moneyops_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InvoiceServiceStub(object):
    """==================== INVOICE SERVICE ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInvoices = channel.unary_unary(
                '/moneyops.InvoiceService/GetInvoices',
                request_serializer=moneyops__pb2.GetInvoicesRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetInvoicesResponse.FromString,
                _registered_method=True)
        self.CreateInvoice = channel.unary_unary(
                '/moneyops.InvoiceService/CreateInvoice',
                request_serializer=moneyops__pb2.CreateInvoiceRequest.SerializeToString,
                response_deserializer=moneyops__pb2.CreateInvoiceResponse.FromString,
                _registered_method=True)
        self.UpdateInvoice = channel.unary_unary(
                '/moneyops.InvoiceService/UpdateInvoice',
                request_serializer=moneyops__pb2.UpdateInvoiceRequest.SerializeToString,
                response_deserializer=moneyops__pb2.UpdateInvoiceResponse.FromString,
                _registered_method=True)
        self.MarkPaid = channel.unary_unary(
                '/moneyops.InvoiceService/MarkPaid',
                request_serializer=moneyops__pb2.MarkPaidRequest.SerializeToString,
                response_deserializer=moneyops__pb2.MarkPaidResponse.FromString,
                _registered_method=True)
        self.GetInvoiceById = channel.unary_unary(
                '/moneyops.InvoiceService/GetInvoiceById',
                request_serializer=moneyops__pb2.GetInvoiceByIdRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetInvoiceByIdResponse.FromString,
                _registered_method=True)


class InvoiceServiceServicer(object):
    """==================== INVOICE SERVICE ====================
    """

    def GetInvoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkPaid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInvoiceById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInvoices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvoices,
                    request_deserializer=moneyops__pb2.GetInvoicesRequest.FromString,
                    response_serializer=moneyops__pb2.GetInvoicesResponse.SerializeToString,
            ),
            'CreateInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInvoice,
                    request_deserializer=moneyops__pb2.CreateInvoiceRequest.FromString,
                    response_serializer=moneyops__pb2.CreateInvoiceResponse.SerializeToString,
            ),
            'UpdateInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInvoice,
                    request_deserializer=moneyops__pb2.UpdateInvoiceRequest.FromString,
                    response_serializer=moneyops__pb2.UpdateInvoiceResponse.SerializeToString,
            ),
            'MarkPaid': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkPaid,
                    request_deserializer=moneyops__pb2.MarkPaidRequest.FromString,
                    response_serializer=moneyops__pb2.MarkPaidResponse.SerializeToString,
            ),
            'GetInvoiceById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvoiceById,
                    request_deserializer=moneyops__pb2.GetInvoiceByIdRequest.FromString,
                    response_serializer=moneyops__pb2.GetInvoiceByIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moneyops.InvoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moneyops.InvoiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InvoiceService(object):
    """==================== INVOICE SERVICE ====================
    """

    @staticmethod
    def GetInvoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.InvoiceService/GetInvoices',
            moneyops__pb2.GetInvoicesRequest.SerializeToString,
            moneyops__pb2.GetInvoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.InvoiceService/CreateInvoice',
            moneyops__pb2.CreateInvoiceRequest.SerializeToString,
            moneyops__pb2.CreateInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.InvoiceService/UpdateInvoice',
            moneyops__pb2.UpdateInvoiceRequest.SerializeToString,
            moneyops__pb2.UpdateInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkPaid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.InvoiceService/MarkPaid',
            moneyops__pb2.MarkPaidRequest.SerializeToString,
            moneyops__pb2.MarkPaidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInvoiceById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.InvoiceService/GetInvoiceById',
            moneyops__pb2.GetInvoiceByIdRequest.SerializeToString,
            moneyops__pb2.GetInvoiceByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ComplianceServiceStub(object):
    """==================== COMPLIANCE SERVICE ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetComplianceDeadlines = channel.unary_unary(
                '/moneyops.ComplianceService/GetComplianceDeadlines',
                request_serializer=moneyops__pb2.GetComplianceDeadlinesRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetComplianceDeadlinesResponse.FromString,
                _registered_method=True)
        self.CalculateGST = channel.unary_unary(
                '/moneyops.ComplianceService/CalculateGST',
                request_serializer=moneyops__pb2.CalculateGSTRequest.SerializeToString,
                response_deserializer=moneyops__pb2.CalculateGSTResponse.FromString,
                _registered_method=True)
        self.GetGSTStatus = channel.unary_unary(
                '/moneyops.ComplianceService/GetGSTStatus',
                request_serializer=moneyops__pb2.GetGSTStatusRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetGSTStatusResponse.FromString,
                _registered_method=True)
        self.ReconcileGST = channel.unary_unary(
                '/moneyops.ComplianceService/ReconcileGST',
                request_serializer=moneyops__pb2.ReconcileGSTRequest.SerializeToString,
                response_deserializer=moneyops__pb2.ReconcileGSTResponse.FromString,
                _registered_method=True)


class ComplianceServiceServicer(object):
    """==================== COMPLIANCE SERVICE ====================
    """

    def GetComplianceDeadlines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateGST(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGSTStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileGST(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComplianceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetComplianceDeadlines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComplianceDeadlines,
                    request_deserializer=moneyops__pb2.GetComplianceDeadlinesRequest.FromString,
                    response_serializer=moneyops__pb2.GetComplianceDeadlinesResponse.SerializeToString,
            ),
            'CalculateGST': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateGST,
                    request_deserializer=moneyops__pb2.CalculateGSTRequest.FromString,
                    response_serializer=moneyops__pb2.CalculateGSTResponse.SerializeToString,
            ),
            'GetGSTStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGSTStatus,
                    request_deserializer=moneyops__pb2.GetGSTStatusRequest.FromString,
                    response_serializer=moneyops__pb2.GetGSTStatusResponse.SerializeToString,
            ),
            'ReconcileGST': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileGST,
                    request_deserializer=moneyops__pb2.ReconcileGSTRequest.FromString,
                    response_serializer=moneyops__pb2.ReconcileGSTResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moneyops.ComplianceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moneyops.ComplianceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComplianceService(object):
    """==================== COMPLIANCE SERVICE ====================
    """

    @staticmethod
    def GetComplianceDeadlines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.ComplianceService/GetComplianceDeadlines',
            moneyops__pb2.GetComplianceDeadlinesRequest.SerializeToString,
            moneyops__pb2.GetComplianceDeadlinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateGST(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.ComplianceService/CalculateGST',
            moneyops__pb2.CalculateGSTRequest.SerializeToString,
            moneyops__pb2.CalculateGSTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGSTStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.ComplianceService/GetGSTStatus',
            moneyops__pb2.GetGSTStatusRequest.SerializeToString,
            moneyops__pb2.GetGSTStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcileGST(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.ComplianceService/ReconcileGST',
            moneyops__pb2.ReconcileGSTRequest.SerializeToString,
            moneyops__pb2.ReconcileGSTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CollectionsServiceStub(object):
    """==================== COLLECTIONS SERVICE ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendReminders = channel.unary_unary(
                '/moneyops.CollectionsService/SendReminders',
                request_serializer=moneyops__pb2.SendRemindersRequest.SerializeToString,
                response_deserializer=moneyops__pb2.SendRemindersResponse.FromString,
                _registered_method=True)
        self.EscalateOverdue = channel.unary_unary(
                '/moneyops.CollectionsService/EscalateOverdue',
                request_serializer=moneyops__pb2.EscalateOverdueRequest.SerializeToString,
                response_deserializer=moneyops__pb2.EscalateOverdueResponse.FromString,
                _registered_method=True)
        self.GetAgingReport = channel.unary_unary(
                '/moneyops.CollectionsService/GetAgingReport',
                request_serializer=moneyops__pb2.GetAgingReportRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetAgingReportResponse.FromString,
                _registered_method=True)
        self.GetCollectionsDashboard = channel.unary_unary(
                '/moneyops.CollectionsService/GetCollectionsDashboard',
                request_serializer=moneyops__pb2.GetCollectionsDashboardRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetCollectionsDashboardResponse.FromString,
                _registered_method=True)


class CollectionsServiceServicer(object):
    """==================== COLLECTIONS SERVICE ====================
    """

    def SendReminders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EscalateOverdue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgingReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionsDashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendReminders': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReminders,
                    request_deserializer=moneyops__pb2.SendRemindersRequest.FromString,
                    response_serializer=moneyops__pb2.SendRemindersResponse.SerializeToString,
            ),
            'EscalateOverdue': grpc.unary_unary_rpc_method_handler(
                    servicer.EscalateOverdue,
                    request_deserializer=moneyops__pb2.EscalateOverdueRequest.FromString,
                    response_serializer=moneyops__pb2.EscalateOverdueResponse.SerializeToString,
            ),
            'GetAgingReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgingReport,
                    request_deserializer=moneyops__pb2.GetAgingReportRequest.FromString,
                    response_serializer=moneyops__pb2.GetAgingReportResponse.SerializeToString,
            ),
            'GetCollectionsDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionsDashboard,
                    request_deserializer=moneyops__pb2.GetCollectionsDashboardRequest.FromString,
                    response_serializer=moneyops__pb2.GetCollectionsDashboardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moneyops.CollectionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moneyops.CollectionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollectionsService(object):
    """==================== COLLECTIONS SERVICE ====================
    """

    @staticmethod
    def SendReminders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.CollectionsService/SendReminders',
            moneyops__pb2.SendRemindersRequest.SerializeToString,
            moneyops__pb2.SendRemindersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EscalateOverdue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.CollectionsService/EscalateOverdue',
            moneyops__pb2.EscalateOverdueRequest.SerializeToString,
            moneyops__pb2.EscalateOverdueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgingReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.CollectionsService/GetAgingReport',
            moneyops__pb2.GetAgingReportRequest.SerializeToString,
            moneyops__pb2.GetAgingReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionsDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.CollectionsService/GetCollectionsDashboard',
            moneyops__pb2.GetCollectionsDashboardRequest.SerializeToString,
            moneyops__pb2.GetCollectionsDashboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TreDSServiceStub(object):
    """==================== TReDS SERVICE (Working Capital) ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEligibleInvoices = channel.unary_unary(
                '/moneyops.TreDSService/GetEligibleInvoices',
                request_serializer=moneyops__pb2.GetEligibleInvoicesRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetEligibleInvoicesResponse.FromString,
                _registered_method=True)
        self.DiscountInvoice = channel.unary_unary(
                '/moneyops.TreDSService/DiscountInvoice',
                request_serializer=moneyops__pb2.DiscountInvoiceRequest.SerializeToString,
                response_deserializer=moneyops__pb2.DiscountInvoiceResponse.FromString,
                _registered_method=True)
        self.GetDiscountingRates = channel.unary_unary(
                '/moneyops.TreDSService/GetDiscountingRates',
                request_serializer=moneyops__pb2.GetDiscountingRatesRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetDiscountingRatesResponse.FromString,
                _registered_method=True)
        self.GetTReDSStatus = channel.unary_unary(
                '/moneyops.TreDSService/GetTReDSStatus',
                request_serializer=moneyops__pb2.GetTReDSStatusRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetTReDSStatusResponse.FromString,
                _registered_method=True)


class TreDSServiceServicer(object):
    """==================== TReDS SERVICE (Working Capital) ====================
    """

    def GetEligibleInvoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscountInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiscountingRates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTReDSStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TreDSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEligibleInvoices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEligibleInvoices,
                    request_deserializer=moneyops__pb2.GetEligibleInvoicesRequest.FromString,
                    response_serializer=moneyops__pb2.GetEligibleInvoicesResponse.SerializeToString,
            ),
            'DiscountInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscountInvoice,
                    request_deserializer=moneyops__pb2.DiscountInvoiceRequest.FromString,
                    response_serializer=moneyops__pb2.DiscountInvoiceResponse.SerializeToString,
            ),
            'GetDiscountingRates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiscountingRates,
                    request_deserializer=moneyops__pb2.GetDiscountingRatesRequest.FromString,
                    response_serializer=moneyops__pb2.GetDiscountingRatesResponse.SerializeToString,
            ),
            'GetTReDSStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTReDSStatus,
                    request_deserializer=moneyops__pb2.GetTReDSStatusRequest.FromString,
                    response_serializer=moneyops__pb2.GetTReDSStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moneyops.TreDSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moneyops.TreDSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TreDSService(object):
    """==================== TReDS SERVICE (Working Capital) ====================
    """

    @staticmethod
    def GetEligibleInvoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.TreDSService/GetEligibleInvoices',
            moneyops__pb2.GetEligibleInvoicesRequest.SerializeToString,
            moneyops__pb2.GetEligibleInvoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscountInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.TreDSService/DiscountInvoice',
            moneyops__pb2.DiscountInvoiceRequest.SerializeToString,
            moneyops__pb2.DiscountInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDiscountingRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.TreDSService/GetDiscountingRates',
            moneyops__pb2.GetDiscountingRatesRequest.SerializeToString,
            moneyops__pb2.GetDiscountingRatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTReDSStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.TreDSService/GetTReDSStatus',
            moneyops__pb2.GetTReDSStatusRequest.SerializeToString,
            moneyops__pb2.GetTReDSStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AccountAggregatorServiceStub(object):
    """==================== ACCOUNT AGGREGATION SERVICE ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccountBalances = channel.unary_unary(
                '/moneyops.AccountAggregatorService/GetAccountBalances',
                request_serializer=moneyops__pb2.GetAccountBalancesRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetAccountBalancesResponse.FromString,
                _registered_method=True)
        self.GetTransactions = channel.unary_unary(
                '/moneyops.AccountAggregatorService/GetTransactions',
                request_serializer=moneyops__pb2.GetTransactionsRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetTransactionsResponse.FromString,
                _registered_method=True)
        self.LinkAccount = channel.unary_unary(
                '/moneyops.AccountAggregatorService/LinkAccount',
                request_serializer=moneyops__pb2.LinkAccountRequest.SerializeToString,
                response_deserializer=moneyops__pb2.LinkAccountResponse.FromString,
                _registered_method=True)


class AccountAggregatorServiceServicer(object):
    """==================== ACCOUNT AGGREGATION SERVICE ====================
    """

    def GetAccountBalances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountAggregatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccountBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountBalances,
                    request_deserializer=moneyops__pb2.GetAccountBalancesRequest.FromString,
                    response_serializer=moneyops__pb2.GetAccountBalancesResponse.SerializeToString,
            ),
            'GetTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactions,
                    request_deserializer=moneyops__pb2.GetTransactionsRequest.FromString,
                    response_serializer=moneyops__pb2.GetTransactionsResponse.SerializeToString,
            ),
            'LinkAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkAccount,
                    request_deserializer=moneyops__pb2.LinkAccountRequest.FromString,
                    response_serializer=moneyops__pb2.LinkAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moneyops.AccountAggregatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moneyops.AccountAggregatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountAggregatorService(object):
    """==================== ACCOUNT AGGREGATION SERVICE ====================
    """

    @staticmethod
    def GetAccountBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.AccountAggregatorService/GetAccountBalances',
            moneyops__pb2.GetAccountBalancesRequest.SerializeToString,
            moneyops__pb2.GetAccountBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.AccountAggregatorService/GetTransactions',
            moneyops__pb2.GetTransactionsRequest.SerializeToString,
            moneyops__pb2.GetTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.AccountAggregatorService/LinkAccount',
            moneyops__pb2.LinkAccountRequest.SerializeToString,
            moneyops__pb2.LinkAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FinanceMetricsServiceStub(object):
    """==================== FINANCE METRICS SERVICE ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetrics = channel.unary_unary(
                '/moneyops.FinanceMetricsService/GetMetrics',
                request_serializer=moneyops__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetMetricsResponse.FromString,
                _registered_method=True)
        self.GetTransactionHistory = channel.unary_unary(
                '/moneyops.FinanceMetricsService/GetTransactionHistory',
                request_serializer=moneyops__pb2.GetTransactionHistoryRequest.SerializeToString,
                response_deserializer=moneyops__pb2.GetTransactionHistoryResponse.FromString,
                _registered_method=True)


class FinanceMetricsServiceServicer(object):
    """==================== FINANCE METRICS SERVICE ====================
    """

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinanceMetricsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=moneyops__pb2.GetMetricsRequest.FromString,
                    response_serializer=moneyops__pb2.GetMetricsResponse.SerializeToString,
            ),
            'GetTransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionHistory,
                    request_deserializer=moneyops__pb2.GetTransactionHistoryRequest.FromString,
                    response_serializer=moneyops__pb2.GetTransactionHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moneyops.FinanceMetricsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moneyops.FinanceMetricsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinanceMetricsService(object):
    """==================== FINANCE METRICS SERVICE ====================
    """

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.FinanceMetricsService/GetMetrics',
            moneyops__pb2.GetMetricsRequest.SerializeToString,
            moneyops__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moneyops.FinanceMetricsService/GetTransactionHistory',
            moneyops__pb2.GetTransactionHistoryRequest.SerializeToString,
            moneyops__pb2.GetTransactionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
